[package]
name = "my_jvm"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.2"
num_cpus = "1.13.1"
rand = "0.8.5"